Movie gain tiff flipping
I2PC/scipion-em-xmipp pull request #380
Opened 2021-03-18 14:24 UTC by DaniDelHoyo

Manages the tiff movies flipping issues.

2021-03-18 14:27 UTC, DaniDelHoyo commented
As a minor comment, the functions flipYGain, applyTransform, rotation, readImage are repeated and should be placed in some utils file and imported.

2021-03-18 14:28 UTC, DaniDelHoyo commented
As a minor comment, the functions flipYGain, applyTransform, rotation, readImage are repeated and should be placed in some utils file and imported. Which "utils" file do you think we can send them to?

2021-03-18 14:37 UTC, DStrelak requested changes

2021-03-18 14:37 UTC, DStrelak commented on xmipp3/protocols/protocol_movie_correlation.py
> +def rotation(imag, angle, shape, P):
this protocol is not a right place for this code. Here it cannot be reused

2021-03-18 14:37 UTC, DStrelak commented on xmipp3/protocols/protocol_movie_correlation.py
> +def applyTransform(imag_array, M, shape):
doesn't seem to be called

2021-03-18 14:37 UTC, DStrelak commented on xmipp3/protocols/protocol_movie_gain.py
> +    def flipYGain(self, gainFn, outFn=None):
duplicated code

2021-03-18 14:37 UTC, DStrelak commented on xmipp3/protocols/protocol_movie_correlation.py
> +              self.flipY = True
what if I don't want to flip the gain? This should be settable from GUI

2021-03-18 14:43 UTC, DaniDelHoyo commented on xmipp3/protocols/protocol_movie_gain.py
> +    def flipYGain(self, gainFn, outFn=None):
yes, as I have said in the comments, this functions should be moved into some "utils" file so they are not duplicated and can be reused, but I don't know where exactly. Any suggestions?

2021-03-18 14:46 UTC, DaniDelHoyo commented on xmipp3/protocols/protocol_movie_correlation.py
> +              self.flipY = True
Indeed I think it would be a good idea to set an extra GUI option for additional flips or rotations as there are in other movie alignment protocols such as motioncorr2, unblur, relion. 
However, we already had a big discussion ( https://github.com/scipion-em/scipion-em/pull/202 ) about how to manage the flips and it was decided to address it this way for tiff movies, assuming you have used movie gain it will work. Assuming you have not used movie gain, flipping it or not will not guaranty a good gain correction.

2021-03-18 14:50 UTC, DStrelak commented
> Which "utils" file do you think we can send them to?

No idea, the best candidate is `convert/convert.py`, but I don't think it's the right place. Try asking somebody from Scipion team, this looks like a sufficiently general functionality.

2021-03-18 14:53 UTC, DStrelak commented on xmipp3/protocols/protocol_movie_correlation.py
> +              self.flipY = True
TLDR (scipion-em/scipion-em#202 );
If we do something by default for user, it makes user happy. If user cannot change default value at all, user is miserable. 
It has to be possible to turn off automatic flip from GUI.

2021-03-18 15:18 UTC, DaniDelHoyo commented on xmipp3/protocols/protocol_movie_correlation.py
> +              self.flipY = True
I agree user must be able to perform further rotations or flips as in other movie alignment protocols. I will implement them in the next version, while I relocate the duplicated functions

2021-03-18 16:35 UTC, DaniDelHoyo commented on xmipp3/protocols/protocol_movie_correlation.py
> +              self.flipY = True
user happy now

2021-03-22 09:09 UTC, DStrelak approved these changes
I've also updated sonarcloud rules, you should see less code smells after next analysis

2021-03-22 09:09 UTC, DStrelak commented on xmipp3/protocols/protocol_movie_gain.py
> +    def flipYGain(self, gainFn, outFn=None):
so why don't you extract this `flipYGain` into the `xmipp3/utils.py` as e.g. `flip(file, newName)`?

2021-03-22 12:03 UTC, DaniDelHoyo commented
The test of this protocol has been adapted and the flipYGain (now flipYImage) has been moved to xmipp3/utils.
If now further changes are requested I think we can successfully and finally approve this PR

2021-03-22 13:34 UTC, DStrelak approved these changes

2021-03-22 18:40 UTC, merged