Fix gpu 2d classification tests
I2PC/scipion-em-xmipp pull request #402
Opened 2021-04-21 14:58 UTC by pconesa

Use waitoutput and run with 4 mpis
Simplify inheritance

2021-04-21 14:59 UTC, pconesa commented
You re going to need today's change (already in devel) of pyworkflow.

2021-04-21 15:09 UTC, DStrelak requested changes

2021-04-21 15:09 UTC, DStrelak commented on xmipp3/tests/test_protocols_gpuCorr_fullStreaming.py
> +class GpuCorrCommon(BaseTest):
Doesn't this change produce a third test (one for GPUCorrCommon, which will fail because of the undefined `verify_classification`) + the original tests?

2021-04-21 15:09 UTC, DStrelak commented on xmipp3/tests/test_protocols_gpuCorr_semiStreaming.py
> -                                 protImportAvgs.outputAverages.getSize(),
test of returned number of classes is missing

2021-04-21 17:17 UTC, pconesa commented on xmipp3/tests/test_protocols_gpuCorr_semiStreaming.py
> -                                 protImportAvgs.outputAverages.getSize(),
It was duplicated, see bellow (hidden by github)

2021-04-21 17:18 UTC, pconesa commented on xmipp3/tests/test_protocols_gpuCorr_semiStreaming.py
> -                                 protImportAvgs.outputAverages.getSize(),
https://github.com/I2PC/scipion-em-xmipp/pull/402/files#diff-39226526ebf450b685e85441271481ce50d41e9cb809f070730b2fe7712ef1d3L73

2021-04-22 10:52 UTC, DStrelak approved these changes

2021-04-22 10:52 UTC, merged