FSO protocol viewer updated adn bfactor viewer
I2PC/scipion-em-xmipp pull request #404
Opened 2021-04-23 11:56 UTC by Vilax

2021-04-26 13:02 UTC, DStrelak requested changes

2021-04-26 13:02 UTC, DStrelak commented on xmipp3/viewers/viewer_resolution_fso.py
> +        lowlim = values.min()
`lowlim = max(0.0, values.min()-stp)`
and skip the code below

2021-04-26 15:25 UTC, Vilax commented on xmipp3/viewers/viewer_resolution_bfactor.py
> +        plt.imshow(bf.reshape(1, len(bf)), cmap=plt.cm.viridis, extent=[r[0], r[-1], 0, 40])
I do not, this is correct

2021-04-26 15:25 UTC, Vilax commented on xmipp3/viewers/viewer_resolution_bfactor.py
> +        plt.imshow(lr.reshape(1, len(lr)), cmap=plt.cm.viridis, extent=[r[0], r[-1], 0, 40])
I do not, this is correct

2021-04-28 13:53 UTC, Vilax commented on xmipp3/viewers/viewer_resolution_bfactor.py
> +        form.addParam('doShowColorBands', LabelParam,
this is the only place that appears, and I do not expect other methos use it

2021-04-28 14:13 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_bfactor.py
> +            params += ' --hasMedian '
useMedian

2021-04-29 12:21 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_bfactor.py
> +                           ' can be a normalized local resolution map, in this case'
Now it was fixed, there was a wrong label

2021-04-29 12:38 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_bfactor.py
> +                           ' can be a normalized local resolution map, in this case'
Yes that is correct. The input can be normalized or not normalized. They are different maps, if the input is not normalized, the user have to normalized.

2021-04-29 12:49 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_bfactor.py
> +        params = ' --atmodel %s' % self.pdbfile.get().getFileName()
I do not understand... you mean use "" instead of ' '?

2021-04-29 12:50 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_fso.py
> +        outputFileName = outputFileName+':mrc'
it is correct, I'm unsure the input is understood as volume and not as stack

2021-04-29 12:52 UTC, pconesa commented on xmipp3/protocols/protocol_resolution_bfactor.py
> +        params = ' --atmodel %s' % self.pdbfile.get().getFileName()
Enclose the filename with "" in case there are spaces in the name.

` --atmodel "%s"' % self.pdbfile.get().getFileName()`

2021-04-29 12:53 UTC, Vilax commented on xmipp3/viewers/viewer_resolution_fso.py
> +        The horizontal axis is linear in this plot. Note
In general when the FSC is plotted, the horizontal axis is not linear. That's why I wrote a note

2021-04-29 12:59 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_bfactor.py
> +        params = ' --atmodel %s' % self.pdbfile.get().getFileName()
Understood, thanks!

2021-04-29 15:46 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_fso.py
> +        params = ' -i %s' % fileName
solved

2021-04-29 16:58 UTC, Vilax commented on xmipp3/viewers/viewer_resolution_fso.py
> +        # sliceNumber has no sense to start in zero
No, I do not set to -1 I rest 1, because we start counting in 0.

2021-04-29 17:16 UTC, Vilax commented on xmipp3/viewers/viewer_resolution_fso.py
> +        if (not idx_x.any()):
sorry... I do not follow you

2021-05-10 13:10 UTC, DStrelak requested changes

2021-05-10 13:10 UTC, DStrelak commented on xmipp3/protocols/protocol_resolution_fso.py
> +                           'An angle of 17 degrees is the best angle to measuare directional FSCs')
some reasoning why 17 degrees is the best would be appreciated

2021-05-10 13:10 UTC, DStrelak commented on xmipp3/protocols/protocol_resolution_fso.py
> +            params = ' -i %s' % fileName
file names should be within `""`

2021-05-12 12:43 UTC, DStrelak submitted a review, later dismissed

2021-05-20 13:31 UTC, pconesa submitted a review, later dismissed

2021-06-05 10:04 UTC, DStrelak approved these changes

2021-06-05 10:04 UTC, merged