Ignore viewer for protocol_deep_align.py
I2PC/scipion-em-xmipp pull request #409
Opened 2021-05-04 19:57 UTC by DaniDelHoyo

until cv2 dependency is removed.

2021-05-05 10:46 UTC, DaniDelHoyo commented
These last changes should remove the cv2 dependency. However, I am not 100% sure that cv2.warpAffine and our ImageHandler applyTransform will equally behave in these transformations, especially because of the borderMode argument, which is not the same as our doWarp.

2021-05-05 10:59 UTC, cossorzano commented
This difference at the borders should not make an important difference in the network training

2021-05-05 10:59 UTC, cossorzano approved these changes

2021-05-05 14:27 UTC, DStrelak requested changes

2021-05-05 14:27 UTC, DStrelak commented on xmipp3/protocols/protocol_deep_align.py
> +                    self._ih.applyTransform(fnImg, newFn, M, (Ydim, Xdim), doWrap=True)
these changes are not equivalent. newImage is not updated. newFn is not written.

2021-05-05 15:45 UTC, DaniDelHoyo commented on xmipp3/protocols/protocol_deep_align.py
> +                    self._ih.applyTransform(fnImg, newFn, M, (Ydim, Xdim), doWrap=True)
newImage was just used for saving the newFn, which it is written. But I do commented the definition of newFn, it is corrected now. And the commented lines are removed.

2021-05-06 15:34 UTC, DStrelak approved these changes

2021-05-17 08:51 UTC, DaniDelHoyo commented
Because of previous "code smells" (I din't introduce any new) it cannot be directly merged. @DStrelak , could you please take a look?
It solves #https://github.com/I2PC/scipion-em-xmipp/issues/408

2021-05-18 08:11 UTC, merged