Shift particles
I2PC/scipion-em-xmipp pull request #410
Opened 2021-05-11 14:26 UTC by EstrellaFG

Protocol for new Xmipp program (PR https://github.com/I2PC/xmipp/pull/386) to center particles 2D in a point selected in a volume, a wizard is provided to do so.

2021-05-12 15:54 UTC, DStrelak requested changes

2021-05-12 15:54 UTC, DStrelak commented on xmipp3/protocols/protocol_shift_particles.py
> +        form.addParam('x', IntParam, label="x", help='Use the wizard to select by clicking in the volume the new '
https://sonarcloud.io/project/issues?id=ScipionEmXmipp&issues=AXlb09yRDQgNC71mZqmy&open=AXlb09yRDQgNC71mZqmy&pullRequest=410

2021-05-12 15:54 UTC, DStrelak commented on xmipp3/protocols/protocol_shift_particles.py
> +        """convert input particles into .xmd file """
what are you doing here? Can't you directly use the original metadata as an input, instead of creating an intermediary?

2021-05-12 15:54 UTC, DStrelak commented on xmipp3/protocols/protocol_shift_particles.py
> +        newFn = row.getValue(md.MDL_IMAGE)
why are you updating the metadata? It should be job of the program

2021-05-13 09:02 UTC, EstrellaFG commented on xmipp3/protocols/protocol_shift_particles.py
> +                      help='Select the SetOfParticles with transformation matrix to be shifted.')
The rotation matrix of each particle is needed to project the 3D shift in the direction of the particle in order to obtain the correspondent 2D shift for each particle

2021-05-13 09:04 UTC, EstrellaFG commented on xmipp3/protocols/protocol_shift_particles.py
> +        """convert input particles into .xmd file """
The input is the scipion object SetOfParticles, so it isn't any input dataset. I am just creating an intermediate dataset with the minimun required info to work with it in the xmipp program.

2021-05-13 12:18 UTC, DStrelak requested changes

2021-05-13 12:18 UTC, DStrelak commented on xmipp3/protocols/protocol_shift_particles.py
> +        """convert input particles into .xmd file """
But that set of particles, I assume, consists of particles, which are stored somehow somewhere, probably as an xmd file already, no?

2021-05-13 14:31 UTC, EstrellaFG commented
In the case of my project they are stored just in a sqlite when imported

2021-05-18 08:06 UTC, DStrelak commented on xmipp3/protocols/protocol_shift_particles.py
> +        args = '-i %s -o %s --shift_to %f %f %f --apply_transform --dont_wrap ' % \
paths strings should be wrapped in `""` (multiple occurrences)

2021-05-18 15:31 UTC, DStrelak requested changes

2021-05-18 15:31 UTC, DStrelak commented on xmipp3/protocols/protocol_shift_particles.py
> +            self.runJob('xmipp_transform_window', '-i %s -o %s --size %d %d %d --save_metadata_stack' %
file paths should be in `""` (multiple occurrences)

2021-05-19 09:18 UTC, DStrelak approved these changes

2021-05-19 09:52 UTC, merged