bug fixing for release
I2PC/scipion-em-xmipp pull request #420
Opened 2021-06-27 18:54 UTC by Vilax

2021-06-28 09:28 UTC, pconesa commented on xmipp3/protocols/protocol_resolution_fso.py
> +            return outputFileName+':mrc'
What is the main reason for adding :mrc
Is it for the viewer?

This kind of paths are later on problematic when used by other plugins....I rather try to avoid :mrc.

2021-06-28 09:31 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_fso.py
> +            return outputFileName+':mrc'
This :mrc only affects on this protocol, it is not the output of the protocol. No problems are expected outside or in other parts of Xmipp/Scipion

2021-06-28 09:32 UTC, pconesa commented on xmipp3/protocols/protocol_resolution_fso.py
> +            return outputFileName+':mrc'
Foerget this. this is for xmipp to understand it. I'm fine with this.

2021-06-28 09:36 UTC, fonsecareyna82 approved these changes

2021-06-28 10:06 UTC, DStrelak requested changes

2021-06-28 10:06 UTC, DStrelak commented on xmipp3/viewers/viewer_resolution_directional.py
> +    """
why are you commenting this?

2021-06-28 10:20 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_monogenic_signal.py
> +        form.addParam('usehalfVolumes', BooleanParam, default=False,
I wouldn't change this now for the release, let's avoid risks

2021-06-28 10:21 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_monogenic_signal.py
> +        form.addParam('hashalfVolumesFile', BooleanParam, default=True,
I wouldn't change this now for the release, let's avoid risks

2021-06-28 10:21 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_monogenic_signal.py
> +            if self.noiseonlyinhalves.get() is True:
I wouldn't change this now for the release, let's avoid risks

2021-06-28 10:25 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_fso.py
> +        errors = []
it does not apply to this case. The father class is empty, and if you keep sailing to more class they do not have validate method

2021-06-28 10:26 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_monogenic_signal.py
>          errors = []
There is not _validate in the parents

2021-06-28 10:27 UTC, Vilax commented on xmipp3/viewers/viewer_resolution_directional.py
> +    """
comments removed

2021-06-28 10:29 UTC, Vilax commented on xmipp3/protocols/protocol_resolution_monogenic_signal.py
> +            if not self.hashalfVolumesFile:
done

2021-06-28 13:09 UTC, pconesa commented on xmipp3/protocols/protocol_resolution_monogenic_signal.py
> +        form.addParam('usehalfVolumes', BooleanParam, default=False,
There is no risk! This will prevent old protocols to be loaded with the right parameters and be rerun for example.

Renaming an existing parameter has this problem:
Existing protocols, will not be properly loaded and therefore can't be resumed, rerun,  or exported.

2021-06-28 13:10 UTC, pconesa commented on xmipp3/protocols/protocol_resolution_monogenic_signal.py
> +        form.addParam('usehalfVolumes', BooleanParam, default=False,
I mean, risk is 0, it will happen, chance is 100%

2021-06-29 12:15 UTC, DStrelak approved these changes

2021-06-29 12:15 UTC, DStrelak commented on xmipp3/protocols/protocol_resolution_monogenic_signal.py
> +        self.halfVolumesFile = DeprecatedParam('hashalfVolumesFile', self)
`hashalfVolumesFile`

2021-06-29 12:15 UTC, DStrelak commented on xmipp3/protocols/protocol_resolution_monogenic_signal.py
> +        group.addParam('maskthreshold', FloatParam, default=0.5,
`maskThreshold`

2021-06-29 12:15 UTC, DStrelak commented on xmipp3/protocols/protocol_resolution_monogenic_signal.py
>          form.addParam('noiseonlyinhalves', BooleanParam, expertLevel=LEVEL_ADVANCED,
`noiseOnlyInHalves`

2021-06-29 12:15 UTC, DStrelak commented on xmipp3/tests/test_protocols_monores.py
> +                                   hasHalfVolumesFile=False,
before this value was `True`. Double check that it's correct now

2021-06-29 14:20 UTC, merged