Multiple threads allowed
I2PC/scipion-em-xmipp pull request #422
Opened 2021-07-02 08:32 UTC by DaniDelHoyo

Couple of changes which avoid  concurrency and fix most of the errors encountered in a deep testing checking:
- 1 thread vs 2 threads
- new model vs pretrained vs previous run
- skip vs not skip training
- do vs don't do preliminar predictions

2021-07-02 08:37 UTC, DStrelak commented
Please create tests for all issues that you have encountered and solved.

2021-07-02 12:28 UTC, DaniDelHoyo commented
I am currently trying a new version which uses a "trafic light" to avoid concurrency problems. This evening I will upload it in this same branch

2021-07-05 10:24 UTC, DStrelak commented
Please fix reported code smells. Let me know if you need help

2021-07-12 11:02 UTC, DStrelak requested changes

2021-07-12 11:02 UTC, DStrelak commented on xmipp3/tests/test_protocol_deepConsensusTesting.py
> +      metacaseKwargs = {'numberOfThreads': 1} if metacase<4 else {'numberOfThreads': 4}
it's not clear what is metacase and case. Please add some documentation

2021-07-12 11:02 UTC, DStrelak commented on xmipp3/tests/test_protocol_deepConsensusTesting.py
> +      nCoordinateSets = 3
here it would be good to say what are your assumptions and expectations, i.e. what you test

2021-07-12 11:33 UTC, DaniDelHoyo commented on xmipp3/protocols/protocol_screen_deepConsensus.py
> +      while self.USING_INPUT_COORDS:
The coordinates are inputs of the protocol, so if they never come I don't know what must happen.
USING_INPUT_COORDS is a traffic light, as we had some concurrency problems with the input coordinates database. It will avoid several concurrent acesses, if somo process is currently using it, the other will wait

2021-07-12 11:35 UTC, DaniDelHoyo commented on xmipp3/protocols/protocol_screen_deepConsensus.py
> +        depsAnd = self.insertExtractPartSteps('AND', prerequisites=[depsAnd])
the first variable is the dependencies of the second line, as the values of the first are never used again, the variable is reused with the new created dependencies. It might be written different if you want

2021-07-12 11:37 UTC, DaniDelHoyo commented on xmipp3/protocols/protocol_screen_deepConsensus.py
> +          makePath(tmpPosDir)
If we have it I don't know it and at least it is not called ensurePath

2021-07-12 13:15 UTC, DaniDelHoyo commented on xmipp3/tests/test_protocol_deepConsensusTesting.py
> +      nCoordinateSets = 3
well, my expectation is that they will not fail... I don't know what else. The thing is there are 3 test where each has a different kind of input so all of them are tested

2021-07-12 14:31 UTC, DStrelak approved these changes

2021-07-12 14:31 UTC, merged