new scheme
I2PC/scipion-em-xmipp pull request #458
Opened 2021-11-24 14:26 UTC by Vilax

2021-11-24 14:38 UTC, EstrellaFG requested changes

2021-11-24 14:38 UTC, EstrellaFG commented on xmipp3/protocols.conf
> +		{"tag": "protocol_group", "text": "Preprocess", "openItem": "False", "children": [
According to the scheme in tomo plugin, this subsection goes inside _Subtomogram Averaging_ section not inside _Particles_ section.

2021-11-24 14:38 UTC, EstrellaFG commented on xmipp3/protocols.conf
>      {"tag": "section", "text": "Postprocessing", "children": [
According to the scheme in tomo plugin, this _Postprocessing_ section should also be a subsection inside _Subtomogram averaging_ section

2021-11-25 10:41 UTC, DStrelak commented
Please follow the naming convention

2021-11-25 11:52 UTC, EstrellaFG approved these changes

2021-11-25 12:57 UTC, EstrellaFG approved these changes

2021-11-25 13:22 UTC, merged