updating bfactor viewer
I2PC/scipion-em-xmipp pull request #462
Opened 2021-11-28 16:06 UTC by Vilax

2021-11-29 09:27 UTC, fonsecareyna82 submitted a review, later dismissed

2021-11-29 10:03 UTC, DStrelak requested changes
Please follow the naming convention

2021-11-29 10:03 UTC, DStrelak commented on xmipp3/viewers/viewer_resolution_bfactor.py
> +        if not self.lowestBF.get():
ternary operator here? 
`low_bf = self.lowestBF if self.lowestBF.get() else bf[0]`

2021-11-29 11:09 UTC, DStrelak commented
> Please follow the naming convention

2021-11-29 11:34 UTC, fonsecareyna82 approved these changes

2021-12-20 15:00 UTC, DStrelak approved these changes

2021-12-20 15:00 UTC, merged