added basic tests for the backend programs used in continuousflex plugin
I2PC/scipion-em-xmipp pull request #464
Opened 2021-12-02 12:56 UTC by MohamadHarastani

This will test the programs xmipp_nma_alignment, xmipp_nma_aligmment_vol and xmipp_volumeset alignment with their MPI versions. However, this test requires continuousflex plugin to be installed.

2021-12-07 11:59 UTC, DStrelak commented
> However, this test requires continuousflex plugin to be installed.

@fonsecareyna82 Is this a problem / can we ensure that we have this plugin on Buildbot when running tests?

2021-12-07 12:01 UTC, DStrelak requested changes

2021-12-07 12:01 UTC, DStrelak commented on xmipp3/tests/test_protocols_continuousflex.py
> +        self.launchProtocol(protAlignment)
So these test check only if the protocol finishes without errors, but do not verify the results. Is that correct?
If yes, can you verify results too?

2021-12-10 13:11 UTC, MohamadHarastani commented on xmipp3/tests/test_protocols_continuousflex.py
> +        self.launchProtocol(protAlignment)
Correct. I don't expect meaningful results from this test other than running the functions correctly. But I can make sure (with assert commands) that the output was correctly stored on the disk. I will take a look at what I can add next week.

2021-12-20 15:02 UTC, DStrelak commented on xmipp3/tests/test_protocols_continuousflex.py
> +        self.launchProtocol(protAlignment)
Hi, any update?
If not, I would consider this PR ready, so that we have at least some tests for the release.

2021-12-21 10:20 UTC, MohamadHarastani commented
Hi David,
I have been very ill for a while, and I will be going on vacation for a
couple of weeks. Today is my last day of work this year and I have some
urgent stuff to do. You can consider it ready for the moment, I can improve
them later next year.

Happy new year in advance, and enjoy your holidays.
Mohamad

On Mon, Dec 20, 2021 at 4:02 PM David Strelak ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In xmipp3/tests/test_protocols_continuousflex.py
> <https://github.com/I2PC/scipion-em-xmipp/pull/464#discussion_r772435933>:
>
> > +                                          numberOfVolumes=2,
> +                                          modeRelationChoice=MODE_RELATION_3CLUSTERS,
> +                                          noiseCTFChoice=1, # not adding noise
> +                                          volumeSize=32)
> +        protSynthesize.inputModes.set(protNMA.outputModes)
> +        protSynthesize.setObjLabel('test images')
> +        self.launchProtocol(protSynthesize)
> +        # ------------------------------------------------
> +        # Lunch HEMNMA on the synthesized images (this will test xmipp_nma_alignment)
> +        # ------------------------------------------------
> +        protAlignment = self.newProtocol(FlexProtAlignmentNMA,
> +                                         modeList='7-8')
> +        protAlignment.inputModes.set(protNMA.outputModes)
> +        protAlignment.inputParticles.set(protSynthesize.outputImages)
> +        protAlignment.setObjLabel('HEMNMA backend')
> +        self.launchProtocol(protAlignment)
>
> Hi, any update?
> If not, I would consider this PR ready, so that we have at least some
> tests for the release.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/I2PC/scipion-em-xmipp/pull/464#discussion_r772435933>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK2I5FM42VBRY7RSW3OJDBDUR5APRANCNFSM5JHBT3TQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2021-12-21 10:44 UTC, DStrelak commented
Hi @MohamadHarastani 
I'm sorry to hear that. I hope you will get better soon!

I will proceed with merge.

Enjoy the holidays and see you soon!

David

2021-12-21 10:45 UTC, DStrelak approved these changes

2021-12-21 10:45 UTC, merged