angular assignment validation
I2PC/scipion-em-xmipp pull request #473
Opened 2022-01-17 13:13 UTC by jeymendez

2022-01-17 14:27 UTC, cossorzano submitted a review, later dismissed

2022-01-26 11:18 UTC, albertmena requested changes

2022-01-26 11:18 UTC, albertmena commented on xmipp3/tests/test_protocol_angular_graph_consistency.py
> +        self.launchProtocol(protValidate)
The test fails to me:
```
 mpirun -np 4  `which xmipp_mpi_transform_mask` -i Runs/000210_XmippProtAngularGraphConsistency/extra/Iter001/globalAssignment/images.stk --mask circular -30
Protocol failed: Command ' mpirun -np 4  `which xmipp_mpi_transform_mask` -i Runs/000210_XmippProtAngularGraphConsistency/extra/Iter001/globalAssignment/images.stk --mask circular -30' returned non-zero exit status 127.
FAILED: globalAssignment, step 3, time 2022-01-26 12:11:02.787882

```

2022-01-26 12:08 UTC, jeymendez commented on xmipp3/protocols/protocol_angular_graph_consistency.py
> +#from pyworkflow.object import Float, String
done

2022-01-26 12:09 UTC, jeymendez commented on xmipp3/protocols/protocol_angular_graph_consistency.py
> +        sym = self.symmetryGroup.get()
done

2022-01-26 13:17 UTC, jeymendez commented on xmipp3/protocols/protocol_angular_graph_consistency.py
> +                i += 1
done

2022-01-26 13:39 UTC, jeymendez commented on xmipp3/protocols/protocol_angular_graph_consistency.py
> +                        fnGalleryGroup = fnGallery = join(fnDirAssignment, "gallery%s_%06d.stk" % (subset, j))
done

2022-01-26 13:46 UTC, jeymendez commented on xmipp3/protocols/protocol_angular_graph_consistency.py
> +        fnDir0 = self._getExtraPath("Iter000")
done

2022-01-26 13:46 UTC, jeymendez commented on xmipp3/protocols/protocol_angular_graph_consistency.py
> +            fnCTFs = ""
done

2022-01-26 13:48 UTC, jeymendez commented on xmipp3/protocols/protocol_angular_graph_consistency.py
> +                        fnGalleryGroup = fnGallery
done

2022-01-26 13:52 UTC, jeymendez commented on xmipp3/protocols/protocol_angular_graph_consistency.py
> +        i=1
done

2022-01-26 13:54 UTC, DStrelak commented
@jeymendez , please click on `Resolve conversation` or simply change the part of the code related to review (which will mark it as outdated). I'm getting way too many emails :D
Also, please first fix your code so that it passes the SonarCloud Analysis, and includes at least basic tests of the functionality. After that, we can do a second round of the reviews.
Feel free to contact either me or @albertmena  if you need to discuss the code in details or need help with those issues.

2022-02-04 16:45 UTC, jeymendez commented on xmipp3/tests/test_protocol_angular_graph_consistency.py
> +        self.launchProtocol(protValidate)
Hi @albertmena,
in my my laptop the test pass correctly. 
I have been trying to install again scipion3 in hertz-dos, in order to try to reproduce the error but i have problems installing it there.
command gcc --version in hertz-dos shows gcc 4 installed... I have compiled and installed in my home folder gcc-10.2 and gcc-8.4 and still having issues compiling xmipp.

2022-02-07 14:40 UTC, DStrelak commented on xmipp3/tests/test_protocol_angular_graph_consistency.py
> +        self.launchProtocol(protValidate)
For me the test passed. 
But it took an hour, which is... not very good.
I'll run some basic profiling to let you know where to have a look

2022-02-07 15:17 UTC, DStrelak commented on xmipp3/tests/test_protocol_angular_graph_consistency.py
> +        self.launchProtocol(protValidate)
So, you spend majority of your time in the `ccMatrix` by `recomputePlanR2C()`.
Get rid of the `CorrelationAux`on line 760 (you don't use i for other things but trosmformer1 anyway), and use some transformer that you store as the class attribute. 
Do not use it for other work but for IFFT.
Check the sizes of your images, consider cropping them to even sizes (i.e. sizex % 2 == 0 && sizey % 2 == 0), as that typically leads to faster processsing.
Like that, you should avoid the penalization of replanning.
Other option is to use `aft.h`, which provides both CPU and CUDA version of FFT.

2022-02-16 10:36 UTC, albertmena commented on xmipp3/tests/test_protocol_angular_graph_consistency.py
> +        self.launchProtocol(protValidate)
now the test pass for me!

2022-02-16 10:39 UTC, albertmena approved these changes

2022-02-17 07:50 UTC, merged