Viewer for standard scipion attributes
I2PC/scipion-em-xmipp pull request #480
Opened 2022-01-20 16:31 UTC by DaniDelHoyo

FSC-Q protocol output is AtomStruct.
Input AtomStruct as object

2022-01-20 16:32 UTC, DaniDelHoyo commented
Los valores por defecto para el rango de fscq he puesto (-3,3), no se si habria que cambiarlo

2022-02-02 10:17 UTC, erneyramirez approved these changes

2022-02-02 11:48 UTC, DStrelak requested changes
PR name does not match the content (this is clearly FSCQ related PR)

2022-02-02 11:59 UTC, DaniDelHoyo commented
> PR name does not match the content (this is clearly FSCQ related PR) 
Hi David, the PR adapts the viewer of the FSC-Q protocol to the general attributes viewer I developed, that's why the name.
If you think the name still must be changed, we'll do it

> Also please add tests for the FCSQ protocol. At least I don't see any at the buildbot.
do you have any test for the protocol @erneyramirez ?

2022-02-02 12:04 UTC, erneyramirez commented
@DStrelak I have to do the test, I had it pending. Pass the PR so Dani can get rid of it and I'll take care of the test

2022-02-02 12:12 UTC, DStrelak commented
> he PR adapts the viewer of the FSC-Q protocol to the general attributes viewer

In that case yes, please change the name of the PR (convention is roughly protocol_name: work_done)

2022-02-02 12:14 UTC, DStrelak commented
> @DStrelak I have to do the test, I had it pending. Pass the PR so Dani can get rid of it and I'll take care of the test

Please accompany this PR with the test directly. It's to avoid a situation in which we have not working code already in the devel.
Alternatively we can put this PR on hold, and you can create the test in a derived branch, eventually merging it to this PR and then to devel.

2022-02-02 14:10 UTC, DaniDelHoyo commented
There you have it, the test and the name is changed

2022-02-07 11:48 UTC, DStrelak requested changes
Test fails with
```
Error: Option -criterio is not defined!
Option errors: 1
Error: Option -criterio is not defined!
Option errors: 1
Traceback (most recent call last):
```

2022-02-07 11:48 UTC, DStrelak commented on xmipp3/protocols/protocol_validate_fscq.py
>                          env=bsoft.Plugin.getEnviron(bsoftVersion=bsoft.V1_9_0))
the version of the program should be defined in a single place

2022-02-07 11:48 UTC, DStrelak commented on xmipp3/protocols/protocol_validate_fscq.py
>                          env=bsoft.Plugin.getEnviron(bsoftVersion=bsoft.V1_9_0))
I also get `Protocol failed: module 'bsoft' has no attribute 'V1_9_0'`

2022-02-14 09:24 UTC, DStrelak approved these changes

2022-02-14 09:50 UTC, merged