Deep consensus update
I2PC/scipion-em-xmipp pull request #483
Opened 2022-01-24 14:19 UTC by danielmarchan3

-Max batch processing to work on bigger datasets
-Training mean val_accuracy threshold to early stop the training 
-Sequential processing instead of parallelization in some importan steps to avoid concurrency
-Fix some bugs

2022-01-24 14:32 UTC, cossorzano submitted a review, later dismissed

2022-01-24 16:57 UTC, DStrelak requested changes
I don't know, it feels like this file has way too many lines of code to 'just do consensus'

2022-01-24 16:57 UTC, DStrelak commented on xmipp3/protocols/protocol_screen_deepConsensus.py
> +            for micFileName in toPreprocessMicFns: # CAMBIOS
`# CAMBIOS` (multiple occurrences)

2022-01-24 16:57 UTC, DStrelak commented on xmipp3/protocols/protocol_screen_deepConsensus.py
> +            print('WARNING: a thread has been waiting for more than a minute to acess the input coordinates')
`access`

2022-01-24 16:57 UTC, DStrelak commented on xmipp3/protocols/protocol_screen_deepConsensus.py
> +          print('WARNING: a thread has been waiting for more than a minute to acess the input micrographs')
`input coordinates`?

2022-01-24 16:57 UTC, DStrelak commented on xmipp3/protocols/protocol_screen_deepConsensus.py
> +            print('Training already finished')
```
if blabla:
    print ...
    return
no_need_for_long_else_here
```

2022-01-24 16:57 UTC, DStrelak commented on xmipp3/protocols/protocol_screen_deepConsensus.py
> +                                                               "are mismatch in coordinate sets filenames"
`there is a mismatch in the coordinate set filenames`

2022-01-24 16:57 UTC, DStrelak commented on xmipp3/protocols/protocol_screen_deepConsensus.py
> +        if trainedParams['trainingPass'] != '':
see my previous comment. By switching the order of the branches and `return`, you avoud this long `if`

2022-01-24 16:57 UTC, DStrelak commented on xmipp3/protocols/protocol_screen_deepConsensus.py
> +            if not micSet == []:
as above. Also, I personally don't like doubly-negative conditions (if not empty)

2022-01-26 16:23 UTC, danielmarchan3 commented
> I don't know, it feels like this file has way too many lines of code to 'just do consensus'

I have the same feeling David, however this protocol does make a lot things different than only a particle picking consensus. Anyway, I will continue working on this protocol, the update was done to make it work on streaming and on big datasets. I am aware that there is still a lot to improve but we are using it in different picking strategies with the ESRF so we need this update in devel branch.

2022-02-01 07:48 UTC, DStrelak approved these changes

2022-02-01 07:48 UTC, merged