consensus clustering 3d: Added functionalities
I2PC/scipion-em-xmipp pull request #497
Opened 2022-04-05 08:02 UTC by oierlauzi

The functionality of the protocol has been expanded to add the following features:

- Iterative intersection ensembling by minimizing a Objective Function
- Automatic class count detection using Full Profile Likelihood, Objective Function's derivative threshold and Objective Function's closeness to origin
- Computation of statistical significance of output class sizes based on a random classification consensus.
- Added visualizations to the viewer

2022-04-06 10:31 UTC, oierlauzi commented
Hello Alberto, I have fixed some issues and updated the tests

2022-04-06 11:25 UTC, albertmena commented
> Hello Alberto, I have fixed some issues and updated the tests

Nice, thanks!

2022-04-11 07:34 UTC, albertmena requested changes
Great job!.
Review the viewer script  and other minor comments

2022-04-11 07:34 UTC, albertmena commented on xmipp3/viewers/viewer_consensus_classes3D.py
> +    def _visualizeDendrogramLog(self, e):
Does not work.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/agarcia/scipion3/scipion-pyworkflow/pyworkflow/gui/form.py", line 1299, in _visualizeVar
    self.visualizeCallback(self.paramName)
  File "/home/agarcia/scipion3/scipion-pyworkflow/pyworkflow/viewer.py", line 265, in _visualizeParam
    views = self._getVisualizeDict()[paramName](paramName)
  File "/home/agarcia/scipion3/xmipp-bundle/src/scipion-em-xmipp/xmipp3/viewers/viewer_consensus_classes3D.py", line 180, in _visualizeDendrogram
    self._plotDendrogram(fig, ax, list(reversed(clusterings)), list(reversed(objectiveFunction)))
  File "/home/agarcia/scipion3/xmipp-bundle/src/scipion-em-xmipp/xmipp3/viewers/viewer_consensus_classes3D.py", line 268, in _plotDendrogram
    hierarchy.dendrogram(linkageMatrix, ax=ax)
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/scipy/cluster/hierarchy.py", line 3301, in dendrogram
    is_valid_linkage(Z, throw=True, name='Z')
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/scipy/cluster/hierarchy.py", line 2280, in is_valid_linkage
    raise ValueError('Linkage %scontains negative distances.' %
ValueError: Linkage 'Z' contains negative distances.
```

2022-04-11 07:34 UTC, albertmena commented on xmipp3/viewers/viewer_consensus_classes3D.py
> +    def _visualizeDendrogram(self, e):
Does not work.

2022-04-11 07:34 UTC, albertmena commented on xmipp3/viewers/viewer_consensus_classes3D.py
> +    def _visualizeReferenceClassificationSizes(self, e):
Does not work.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/agarcia/scipion3/scipion-pyworkflow/pyworkflow/gui/form.py", line 1299, in _visualizeVar
    self.visualizeCallback(self.paramName)
  File "/home/agarcia/scipion3/scipion-pyworkflow/pyworkflow/viewer.py", line 265, in _visualizeParam
    views = self._getVisualizeDict()[paramName](paramName)
  File "/home/agarcia/scipion3/xmipp-bundle/src/scipion-em-xmipp/xmipp3/viewers/viewer_consensus_classes3D.py", line 215, in _visualizeReferenceClassificationSizes
    randomConsensusSizePercentiles = np.percentile(randomConsensusSizes, percentiles)
  File "<__array_function__ internals>", line 5, in percentile
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3705, in percentile
    return _quantile_unchecked(
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3824, in _quantile_unchecked
    r, k = _ureduce(a, func=_quantile_ureduce_func, q=q, axis=axis, out=out,
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3403, in _ureduce
    r = func(a, **kwargs)
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3941, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

```

2022-04-11 07:34 UTC, albertmena commented on xmipp3/viewers/viewer_consensus_classes3D.py
> +        labels = 'enabled id _size _representative._filename _xmipp_classIntersectionSizePValue _xmipp_classIntersectionRelativeSizePValue'
_representative._filename column show red crosses, is that ok?
It happen in all Classes viewers (Initial classes, manual number of classes...)

2022-04-12 13:21 UTC, oierlauzi commented on xmipp3/viewers/viewer_consensus_classes3D.py
> +        labels = 'enabled id _size _representative._filename _xmipp_classIntersectionSizePValue _xmipp_classIntersectionRelativeSizePValue'
If you have used the test project to check it out, yes, its normal. This is because the previous step is not configured to set that attribute. I guess I could modify the test to import a volume from somewhere and use it as the representative.

2022-04-14 08:53 UTC, DStrelak commented on xmipp3/viewers/viewer_consensus_classes3D.py
> +# * Authors:     J.M. De la Rosa Trevin (jmdelarosa@cnb.csic.es)
Who's the author?

2022-04-18 12:37 UTC, albertmena submitted a review, later dismissed

2022-06-02 08:22 UTC, albertmena commented on xmipp3/viewers/viewer_consensus_classes3D.py
> +        labels = 'enabled id _size _representative._filename _xmipp_classIntersectionSizePValue _xmipp_classIntersectionRelativeSizePValue'
The tests must be focus on the _assert_ sentences. Not in the viewers. I was in doubt  if that red crosses meaning something bad in the code.
Thanks

2022-06-02 08:31 UTC, albertmena commented on xmipp3/protocols/protocol_consensus_classes3D.py
> +    def _writeReferenceClassificationRelativeSizes(self, sizes):
Function names with 42 characteres will cause violate pep style guides (lines longer than 79 characters). Better something like __writeRefClassifRelSize(...)_

2022-06-02 08:38 UTC, albertmena approved these changes

2022-06-02 08:38 UTC, albertmena commented on xmipp3/protocols/protocol_consensus_classes3D.py
> +    def _objectiveFunction(self, ns, indices, vs, eps=0.01):
Better use 
```
import sys
sys.float_info.epsilon # 2.220446049250313e-16
```

2022-06-03 07:18 UTC, merged