projection subtraction: remove unneeded params in new implementation
I2PC/scipion-em-xmipp pull request #500
Opened 2022-04-08 10:47 UTC by EstrellaFG

THIS IS NOT A REAL PR, BUT JUST A TEST

2022-05-26 09:07 UTC, albertmena requested changes

2022-05-26 09:07 UTC, albertmena commented on xmipp3/tests/test_protocols_xmipp_3d.py
>          self.launchProtocol(protCreateGallery)
Could you reorder it adding a loop or adding some comments to divide each test, is difficult to follow it and maintenance it.

2022-05-26 09:07 UTC, albertmena commented on xmipp3/tests/test_protocols_xmipp_3d.py
>          self.launchProtocol(protCreateGallery)
Could you reorder it adding a loop or adding some comments to divide each test, is difficult to follow it and maintenance it.

2022-05-26 09:07 UTC, albertmena commented on xmipp3/protocols/protocol_subtract_projection.py
> +    """ This protocol computes the subtraction between particles and a reference volume, by computing its projections
The line break makes difficult to read in the window help

2022-05-26 10:43 UTC, EstrellaFG commented on xmipp3/protocols/protocol_subtract_projection.py
>      def _insertAllSteps(self):
I think the protocol has this structure already: 
1. convertStep (equivalent to readInput)
2. subtractionStep (RunCosas -> It is a very short method, I do not think I could divide it more)
3. createOutputStep

2022-05-26 10:56 UTC, albertmena approved these changes

2022-05-26 10:56 UTC, albertmena commented on xmipp3/protocols/protocol_subtract_projection.py
>      def _insertAllSteps(self):
Yes, sorry.

2022-06-03 11:33 UTC, albertmena approved these changes

2022-06-08 10:08 UTC, albertmena requested changes

2022-06-08 13:09 UTC, albertmena approved these changes

2022-06-08 13:09 UTC, merged