New protocol: rotate volume
I2PC/scipion-em-xmipp pull request #512
Opened 2022-05-09 14:25 UTC by EstrellaFG

New protocol for rotation of a volume using `xmipp_transform_geometry --rotate_volume`

2022-05-09 14:35 UTC, pconesa requested changes

2022-05-09 14:35 UTC, pconesa commented on xmipp3/protocols/protocol_rotate_volume.py
> +        outputVol.setLocation(self._getExtraPath('rotated_vol.mrc'))
I think is great to generate mrc files by default. It has a couple fo extra steps to be done.
1.- check the header has the right sampling rate. If I'm right, xmipp mrcs, unless explicitly specified the have 1.0 as sampling rate. the is a function in Image class (Volume belings to it) to setIt ..> outputVol.setMRCSamplingRate(3.0) will set the header of the mrc to 3

2.- Make sure is a volume. Here, maybe xmipp does it right, but is worth checking that the headers as so. A quick inspection of the MRC file in the file browser will tell you if it s a stack or a volume. If is a stack you have outputVol.fixMRCVolume(). Maybe is not necessary here.

2022-05-09 15:23 UTC, pconesa approved these changes

2022-05-10 07:03 UTC, EstrellaFG commented on xmipp3/protocols/protocol_rotate_volume.py
> +        setMRCSamplingRate(outputVol.getFileName(), inputVol.getSamplingRate())
It was not working for me that way, returning error `Protocol failed: setMRCSamplingRate() takes 1 positional argument but 2 were given` (maybe I am doing something wrong)

2022-05-10 08:44 UTC, pconesa commented on xmipp3/protocols/protocol_rotate_volume.py
> +        setMRCSamplingRate(outputVol.getFileName(), inputVol.getSamplingRate())
Yes the signature is different, you dont need to pass the file, since Volume will use its internal attribute.

2022-05-10 08:59 UTC, pconesa commented on xmipp3/protocols/protocol_rotate_volume.py
> +        setMRCSamplingRate(outputVol.getFileName(), inputVol.getSamplingRate())
and sampling rate is taken internally too

2022-05-10 09:00 UTC, merged