Protocol Analyze Local CTF: bugfixing + test + formatting
I2PC/scipion-em-xmipp pull request #535
Opened 2022-06-13 15:32 UTC by EstrellaFG

2022-06-15 09:47 UTC, albertmena requested changes

2022-06-15 09:47 UTC, albertmena commented on xmipp3/protocols/protocol_analyze_local_ctf.py
>      def _summary(self):
You could add a median of the defocus (how to: search summary.txt files), to have a general idea of how it was.

2022-06-15 09:47 UTC, albertmena commented on xmipp3/viewers/viewer_analyze_local_ctf.py
> +        form.addParam('displayLocalDefocus', IntParam, label='Display local defocus of micrograph:', allowsNull=True,
Help identifying the ID of the available micrographs. Or at least ad by default the first (default=1?)

2022-06-15 14:49 UTC, EstrellaFG commented on xmipp3/protocols/protocol_analyze_local_ctf.py
>      def _summary(self):
In this case we have a defocus value for each of the particles and thus has no sense to have a "global" defocus value

2022-06-15 14:51 UTC, EstrellaFG commented on xmipp3/tests/test_protocols_local_defocus.py
> +                         "There was a problem with the sampling rate value of output consensus particles")
What it is computed in this protocol is an R2 coefficient that "compares" the defocus value of the micrograph with the defocus of each particle after the local refinement, but that R2 coeffcient it is not an attribute of the micrograph class, but a new xmipp label added to the xmipp metadata, so it is not accesible through the test (AFAIK)

2022-06-15 14:56 UTC, EstrellaFG commented on xmipp3/viewers/viewer_analyze_local_ctf.py
> +                title="Micrograph %d defocus" % self.displayLocalDefocus.get()
We need a 3D graph because the defocus value for each particle "is equivalent to the height of the particle in the ice", and that is exactly what we want to see in the plot. We want to see both the "real" height for each particle (Avg = average between defocusU and defocusV) and the adjusted plane to see the plane where all particles "should be" if they have equal defocus. The range of the defocus axis can be modified dynamically in the plot, which is usefull as you may want to compare different runnings of this protocol with different defocus estimations as input, and they will produce outputs with different ranges, so you can adjust them dynamically.

2022-06-16 05:57 UTC, albertmena approved these changes

2022-06-16 05:57 UTC, albertmena commented on xmipp3/protocols/protocol_analyze_local_ctf.py
>      def _summary(self):
ok, and maybe the R2?, I dont know if is an interesting parameter to view in the summary

2022-06-16 07:18 UTC, merged