protocol_deep_hand: new test for the protocol
I2PC/scipion-em-xmipp pull request #549
Opened 2022-07-14 07:19 UTC by gemapatricia

2022-07-14 08:17 UTC, EstrellaFG submitted a review, later dismissed

2022-07-19 09:39 UTC, albertmena requested changes
Could you add a validation in this protocol?, just add 

>errors.append( self.validateDLtoolkit()))
in the validate function
thanks

2022-07-19 09:39 UTC, albertmena commented on xmipp3/protocols/protocol_deep_hand.py
> +    vResizedVolFile = 'resizedVol.mrc'
define this params inside the class, _insertAllStep needs functions without params as input.

2022-07-19 09:40 UTC, albertmena commented on xmipp3/protocols/protocol_deep_hand.py
> +    vResizedVolFile = 'resizedVol.mrc'
Also merge devel into current branch to fix the conflict

2022-07-19 11:02 UTC, EstrellaFG commented on xmipp3/protocols/protocol_deep_hand.py
> +        errors.append(self.validateDLtoolkit())
@albertmena is it possible to add a more readable error message ? In my case (i do not have the deeplearning toolkit) I am getting: `'Protocol has validation errors:\n' + '\n'.join(errors))
00006:   TypeError: sequence item 0: expected str instance, list found`, which I guess is correct but I think for the user is better something like "deepLearningToolkit missing" or something similar

2022-07-19 14:08 UTC, EstrellaFG commented on xmipp3/tests/test_protocols_xmipp_3d.py
> +        cls.vol1 = cls.dataset.getFile(vol1_iter2)
remove this line and the line before as they are no longer needed

2022-07-19 14:47 UTC, gemapatricia commented on xmipp3/protocols/protocol_deep_hand.py
> +        #errors.append(self.validateDLtoolkit(model="deepHand"))
Leaving it commented for the moment, because if it is uncommented, the protocol doesn't work

2022-07-19 14:48 UTC, gemapatricia commented on xmipp3/tests/test_protocols_xmipp_3d.py
> +        cls.vol1 = cls.dataset.getFile(vol1_iter2)
Done

2022-07-20 08:54 UTC, EstrellaFG submitted a review, later dismissed

2022-07-20 10:22 UTC, EstrellaFG approved these changes

2022-07-21 06:09 UTC, albertmena approved these changes

2022-07-21 06:09 UTC, merged