New Zernike3D programs
I2PC/scipion-em-xmipp pull request #566
Opened 2022-09-28 11:44 UTC by DavidHerreros

2022-09-28 18:23 UTC, jamesmkrieger commented on xmipp3/protocols/protocol_apply_zernike3d.py
> +# * Authors:     David Herreros Calero (dherreros@cnb.csic.es)
probably I should be here too:
James Krieger (jmkrieger@cnb.csic.es)

2022-09-29 13:06 UTC, DavidHerreros commented on xmipp3/protocols/protocol_apply_zernike3d.py
> +# * Authors:     David Herreros Calero (dherreros@cnb.csic.es)
Added!

2022-09-29 16:04 UTC, jamesmkrieger requested changes
Everything looks good to me except for a few minor documentation things

2022-09-29 16:04 UTC, jamesmkrieger commented on xmipp3/viewers/viewer_pdb_deform_zernike3d.py
> +                      label="Display original and deformed PDB or volume")
This shouldn't say this as we ended up making this viewer only for atomic structures.

2022-09-29 16:04 UTC, jamesmkrieger commented on xmipp3/viewers/viewer_pdb_deform_zernike3d.py
> +                      label="Display a morphing between the original and deformed PDB or volume")
same here

2022-09-29 16:04 UTC, jamesmkrieger commented on xmipp3/viewers/viewer_volume_deform_zernike3d.py
> +                      label='Structure to display', display=params.EnumParam.DISPLAY_COMBO,
This should be volume not structure

2022-10-07 10:16 UTC, jamesmkrieger approved these changes

2022-10-15 13:27 UTC, cossorzano approved these changes

2022-10-15 13:27 UTC, merged