New Validation Algorithm: Detect misalignment with resolution
I2PC/scipion-em-xmipp pull request #639
Opened 2023-03-29 22:52 UTC by Vilax

2023-04-14 07:24 UTC, EstrellaFG requested changes
I think it is a useful program, good job! Requested changes are just minor details that you decide if you should adress them or not :)
Please try to fix sonar cloud code smells and duplication or mark them as "won't fix" if they don't apply, to not add them for futures Xmipp Hunting Days...

2023-04-14 07:24 UTC, EstrellaFG commented on xmipp3/protocols/protocol_angular_resolution_alignment.py
> +    _label = 'resolution alignment'
add "NEW" tag (check it with @albertmena)

2023-04-14 07:24 UTC, EstrellaFG commented on xmipp3/protocols/protocol_angular_resolution_alignment.py
> +        #if hasattr(self, 'resolution_Volume'):
complete it and uncomment or delete commented code (unless it is pending to update it in a near future)

2023-04-14 07:24 UTC, EstrellaFG commented on xmipp3/protocols/protocol_angular_resolution_alignment.py
> +    then the map present angular assignment errors, but it the curve is flat, the map
instead of "curve is flat" (it sounds weird to me, but maybe is more correct) you can say something like "if the graph is flat" or "if it is a straight line"??

2023-04-14 07:24 UTC, EstrellaFG commented on xmipp3/protocols/protocol_angular_resolution_alignment.py
> +    """
The protocol gives no output, I guess it is on purpose, but maybe you can warn it here in the description for users not to get confused

2023-04-14 07:24 UTC, EstrellaFG commented on xmipp3/protocols/protocol_angular_resolution_alignment.py
> +        summary.append(" ")
could you add something to the summary as "radial FSC computed" at least or something like? Again, it is just for the users to not get confused when they see there is no output and no summary info

2023-07-02 19:54 UTC, Vilax commented on xmipp3/protocols/protocol_angular_resolution_alignment.py
> +    _label = 'resolution alignment'
I prefer to wait until the publication, just in case

2023-07-02 19:58 UTC, Vilax commented on xmipp3/protocols/protocol_angular_resolution_alignment.py
> +        #if hasattr(self, 'resolution_Volume'):
done

2023-07-02 19:59 UTC, Vilax commented on xmipp3/protocols/protocol_angular_resolution_alignment.py
> +#    def _citations(self):
done

2023-07-02 20:03 UTC, Vilax commented on xmipp3/protocols/protocol_angular_resolution_alignment.py
> +    then the map present angular assignment errors, but it the curve is flat, the map
done

2023-07-02 20:04 UTC, Vilax commented on xmipp3/protocols/protocol_angular_resolution_alignment.py
> +        summary.append(" ")
done above!

2023-07-02 20:05 UTC, Vilax commented on xmipp3/viewers/viewer_angular_resolution_alignment.py
> +        ##a.xaxis.set_major_formatter(FuncFormatter(self._formatFreq))
done

2023-07-03 06:15 UTC, EstrellaFG submitted a review, later dismissed

2023-07-03 08:26 UTC, albertmena approved these changes

2023-07-03 09:33 UTC, merged