New protocol: Movie Dose analysis
I2PC/scipion-em-xmipp pull request #671
Opened 2023-05-05 11:01 UTC by danielmarchan3

- It estimates the mean dose per angstrom**2 to check how stable is the dose during the acquisition. 
- This can be useful for facilities

2023-05-08 08:09 UTC, albertmena requested changes
Looks great and very useful for facilities!, just some details to fix. Are you planning to run this protocol in streaming?

2023-05-08 08:09 UTC, albertmena commented on xmipp3/protocols/protocol_movie_dose_analysis.py
> +    plt.title('Dose differences with respect to the global median vs time')
Add the units (e⁻/A²) ?

2023-05-08 08:09 UTC, albertmena commented on xmipp3/protocols/protocol_movie_dose_analysis.py
> +    plt.axhline(y=upper, color='b', linestyle='-.', label='Upper limit')
Upper limit **dose**
Lower limit **dose**

2023-05-09 08:07 UTC, danielmarchan3 commented on xmipp3/protocols/protocol_movie_dose_analysis.py
> +    # FIXME: WITH .mrcs IT DOES NOT FILL THE LABELS
Work in progress, not sure why I am having problems with this type of movies format

2023-05-09 10:41 UTC, albertmena approved these changes

2023-05-09 11:23 UTC, merged