Add mask as input. Mask resize is now possible.
I2PC/scipion-em-xmipp pull request #693
Opened 2023-06-07 09:21 UTC by erneyramirez

2023-06-07 09:41 UTC, pconesa commented on xmipp3/protocols/protocol_preprocess/protocol_crop_resize.py
> +        if self.inputParticles.get().getClassName() == 'Mask':
I'd extract this into a singe method 

def isMask():

   return isInstance(self.inputParticles.get(), Mask)

2023-06-07 09:42 UTC, pconesa commented on xmipp3/protocols/protocol_preprocess/protocol_crop_resize.py
> +        if self.inputParticles.get().getClassName() == 'Mask':
and of course use it everyowhere

2023-06-07 09:44 UTC, pconesa commented on xmipp3/protocols/protocol_preprocess/protocol_crop_resize.py
> +                setMRCSamplingRate(self.outputStk, self.samplingRate)
I'd also set de samplingrate of the mask n the mrc file too, providing is an mrc.

2023-06-07 14:07 UTC, MartinSalinas98 commented on xmipp3/protocols/protocol_preprocess/protocol_crop_resize.py
> +        if self.inputParticles.get().getClassName() == 'Mask':
Done

2023-06-07 14:19 UTC, MartinSalinas98 commented on xmipp3/protocols/protocol_preprocess/protocol_crop_resize.py
> +                setMRCSamplingRate(self.outputStk, self.samplingRate)
Hi @pconesa, what do you mean with this? @erneyramirez and I have tried this with a mask which has a .xmd (or similar) extension, which does not work with that function, and we are also doing always `output.setSamplingRate(self.samplingRate)`.
Does that make any difference, and if so, what should we do? Only not run that function for non-mrc Masks, or always try to convert a non-mrc Mask into an mrc?

2023-06-21 09:37 UTC, pconesa commented on xmipp3/protocols/protocol_preprocess/protocol_crop_resize.py
> +                setMRCSamplingRate(self.outputStk, self.samplingRate)
Please, if possible, better generate mrc files. Those functions only apply to mrc files.

2023-06-23 11:07 UTC, pconesa requested changes
I advice some minor changes.

2023-06-23 11:07 UTC, pconesa commented on xmipp3/protocols/protocol_preprocess/protocol_crop_resize.py
> +    _possibleOutputs = {'outputParticles': SetOfParticles, 'outputMask': Mask}
Nice to define possible outputs.

One  suggestion, further down you use "outputMask" again in the defineOutputs. We usually define a constant and use the constant everywhere. Even in tests.

To avoid hasAttr....you can define in the __init__ a None Attribute like self.outputParticles (same for outputMask)

2023-06-23 11:07 UTC, pconesa commented on xmipp3/protocols/protocol_preprocess/protocol_crop_resize.py
> +            self.outputMd = self._getTmpPath('tmp.xmd')
this extension is not right. And there is no conversion here in the case of the mask..it is just filling attributes. Looks confusing.

2023-06-23 11:07 UTC, pconesa commented on xmipp3/protocols/protocol_preprocess/protocol_crop_resize.py
> +    def isMask(self, inputObject):
Why passing a argument it can get from self?

2023-06-23 11:07 UTC, pconesa commented on xmipp3/protocols/protocol_preprocess/protocol_crop_resize.py
> +        return inputObject.getClassName() == 'Mask'
Maybe isInstance will work and avoid AttributeError and the try/except

2023-06-23 11:11 UTC, MartinSalinas98 commented on xmipp3/protocols/protocol_preprocess/protocol_crop_resize.py
> +            self.outputMd = self._getTmpPath('tmp.xmd')
This is because outputMd is used for the metadata file when working with a set of particles. In this case, we redirect it to tmp path so it gets deleted, because we dont need it. We could also override the parent functions where that attribute is referenced and avoid using it when working with masks, but this was way simpler

2023-06-23 11:31 UTC, MartinSalinas98 commented on xmipp3/protocols/protocol_preprocess/protocol_crop_resize.py
> +    def isMask(self, inputObject):
True, done

2023-06-23 11:44 UTC, MartinSalinas98 commented on xmipp3/protocols/protocol_preprocess/protocol_crop_resize.py
> +        return inputObject.getClassName() == 'Mask'
Done

2023-06-29 09:47 UTC, pconesa approved these changes

2023-06-29 09:47 UTC, merged