New protocol: Movie alignment consensus
I2PC/scipion-em-xmipp pull request #771
Opened 2024-02-06 16:10 UTC by danielmarchan3

New protocol for the comparison of two global alignments

2024-02-16 11:29 UTC, albertmena requested changes
The test fails
```  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol_align_movies.py", line 142, in createOutputStep
    raise Exception("All movies failed, didn't create outputMicrographs."
Exception: All movies failed, didn't create outputMicrographs.Please review movie processing steps above.
Protocol failed: All movies failed, didn't create outputMicrographs.Please review movie processing steps above.
```

2024-02-29 09:47 UTC, danielmarchan3 commented
I checked again and ran it with all my repositories updated, and the two tests passed without any problem. Oier, could you please check where the test is failing? Maybe it has something to do with an old version of the Scipion repositories.

2024-05-13 09:20 UTC, albertmena commented
> I checked again and ran it with all my repositories updated, and the two tests passed without any problem. @oierlauzi, could you please check where the test is failing? Maybe it has something to do with an old version of the Scipion repositories.

Now, it works for me

2024-05-14 05:44 UTC, albertmena approved these changes

2024-05-14 05:47 UTC, merged