Generating toml file
I2PC/scipion-em-xmipp pull request #828
Opened 2024-11-21 06:18 UTC by albertmena

https://github.com/I2PC/scipion-em-xmipp/issues/826

2024-11-29 12:11 UTC, oierlauzi requested changes

2024-11-29 12:11 UTC, oierlauzi commented on pyproject.toml
> +    {name = "Alberto Garcia Mena", email = "pconesa@cnb.csic.es"},
Change e-mail

2024-11-29 15:30 UTC, pconesa commented on pyproject.toml
> +    "numpy>=1.21.0",
I think we should not define a dependency already in the core

2024-12-04 09:14 UTC, albertmena commented
Reverting changes because of the logo issue (in release it does not appear because an issue in the scipion toml integration)

2024-12-04 09:43 UTC, albertmena commented
scikit-image is going to appear as dependency: https://github.com/I2PC/scipion-em-xmipp/pull/838/files

2024-12-05 09:12 UTC, oierlauzi approved these changes
AFAIK everything is OK for me, but I am not very familiar with pyproject.toml files.

2024-12-05 09:14 UTC, albertmena commented
> AFAIK everything is OK, but I am not very familiar with pyproject.toml files.

in any case it is not implemented for your current use (rename the project.toml)

2024-12-05 09:15 UTC, merged