managin scipionApp
I2PC/scipion-em-xmipp pull request #866
Opened 2024-12-18 10:52 UTC by albertmena

Check if scipion-app <= 3.7.0 to avoid the installation because of the [ scipion-app bug ](https://github.com/scipion-em/scipion-app/pull/201)

2024-12-18 15:27 UTC, MartinSalinas98 approved these changes

2024-12-18 15:27 UTC, MartinSalinas98 commented on xmipp3/__init__.py
> +        scipionApp = int(''.join(map(str, [int(x) for x in scipionAppVersion.split('.')])))
Overcomplicated. You do:
1. split version string by dots (you get a list of strings)
2. do a for comprehension to convert the list of strings into a list of ints
3. do a map on that list of ints converting them back to a list of strings
4. join them to make them a single string
5. convert the result number string into an int

Why not just do:
```py
int(scipionAppVersion.replace(".", ""))
```
1. Remove dots from the version string
2. convert into int

Still this is not a foolproof method:
Let's say we require scipion-app version `3.7.0`. The methods above would convert it into `370`.
If tomorrow scipion releases scipion `3.8.0`, it would be translated into `380`, which works as intended.
But version `3.6.10` is prior to `3.7.0` in semver's system, however, it gets converted into `3610`, considered greater, and therefore accepted.

2024-12-18 15:27 UTC, MartinSalinas98 commented on xmipp3/__init__.py
> +        scipionApp = int(''.join(map(str, [int(x) for x in scipionAppVersion.split('.')])))
TLDR: use a comparison function:
```py
def meetsRequiredVersion(version, requiredVersion):
    requiredVersionList = requiredVersion.split(".")
    versionList = version.split(".")
    if len(versionList) != len(requiredVersionList):
        # Show error, the version formats do not match
        return False # Or even raise exception
    for versionSegment, minimumVersionSegment in zip(versionList, requiredVersionList):
        if versionSegment < minimumVersionSegment:
            print("Version minimum than required.....")
            return False
    return True
```

2024-12-18 15:27 UTC, MartinSalinas98 requested changes
Approved by mistake

2024-12-18 15:51 UTC, pconesa commented on xmipp3/__init__.py
> +        scipionApp = int(''.join(map(str, [int(x) for x in scipionAppVersion.split('.')])))
This migth be useful: https://packaging.pypa.io/en/latest/version.html#packaging.version.Version

2024-12-18 16:12 UTC, MartinSalinas98 commented on xmipp3/__init__.py
> +        scipionApp = int(''.join(map(str, [int(x) for x in scipionAppVersion.split('.')])))
> This migth be useful: https://packaging.pypa.io/en/latest/version.html#packaging.version.Version

I agree, that's even better, didn't know the standard library came with a version comparator built in

2024-12-19 06:11 UTC, albertmena commented on xmipp3/__init__.py
> +        scipionApp = int(''.join(map(str, [int(x) for x in scipionAppVersion.split('.')])))
Great, thanks both, I included the packaging.version

2024-12-19 06:23 UTC, merged